project:
  name: qs-workshop
  regions:
  - us-east-2
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-east-2

    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: email@yourdomain.com
      KeyPairName: Pat
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

